### ISSUE TITLE
Remove duplicate configuration parameters in schema-watcher

### ISSUE THREAD

**Issue by apilikov** [yandex-cloud/jaeger-ydb-store#17]
Here's an example of a working config for schema-watcher:
```yaml
ydb.sa.meta-auth: "true"
ydb_write_timeout: 10s
ydb.address: lb.cc80**********chgq841.ydb.mdb.****.net:2135
ydb.path: /pre-prod_global/aoe***********6p/cc80***********chgq841
ydb_path: /pre-prod_global/aoe***********6p/cc80***********chgq841
watcher_age: 168h
parts_traces: "4"
parts_idx_tag: "4"
parts_idx_duration: "4"
parts_idx_service_name: "4"
parts_idx_service_op: "4"
ydb_folder: "v2"
ydb_feature_split_by_load: "true"
ydb_feature_compression: "true"
```
It can be clearly seen that at least ydb.path has a duplicate configuration ydb_path and both has to be supplied which is very misleading.
